version: '3'

services:
  nest:
    image: node:20-slim
    container_name: app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    networks:
      - my_network
    command: npm run start:dev

networks:
  my_network:
